# fly.toml app configuration file generated for reactivities-bry on 2023-10-05T13:08:12+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-bry"
primary_region = "syd"

[build]
  image = "bryanng13/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="bryten"
  Cloudinary__ApiKey="432925258774429"
  Facebook__AppId="996127934774894"
  Sendgrid__User="Bryten"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
